### ISSUE TITLE
Enancement: apk download link.

### ISSUE THREAD

**Issue by Techwolf** [klinker24/Talon-for-Twitter#14]
I've tried just about everything I could think of and not found any links to the apk download except for some very questionable sites. F-Droid does not have this. :-(

Please add a download link to a reputable site where one can download and install this program.

**Comment by klinker24** [comment]
No, sorry, I cannot do that.

While this application is open source, it does not contain the necessary API keys to make it work with twitter. You have to generate those yourself.

So while i could post a build, it would do no good. The keys I have used in my production/play store app have run out of tokens, which is why it was open sourced in the first place.

You will have to add your own keys, and build the app yourself if you would like to use it. This repo has instructions on how to do this.
