### ISSUE TITLE
Migration to AppCompat

### ISSUE THREAD

**Issue by Florent1510** [klinker24/Talon-for-Twitter#17]
Hey!

I'm currently trying to update Talon to AppCompat. The Login activity is already working, but MainActivity just struggles and tries to restart and restart. I've already tried to migrate the Drawer Code to AppCompatActivity and v7 ActionBarDrawerToggle.

Do you have an idea about what might be the Problem?

Thanks!

**Comment by klinker24** [comment]
I would imagine it is the ```MainActivity.onStart()``` method causing you
issues. If you don't meet some parameters for UI things, it will fix those
parameters by restarting itself.

Just so you know though, I'm going to close this because I do not plan on
merging any UI changes/updates into Talon classic. The material design
version has the updated UI (along with AppCompat). I simply do not have
enough time to use/test whether or not all the changes and refactoring
required for this sort of thing work.
